---
title: "Job Search Report August-September 2019"
author: 'Samir Benjelloun'
date: '2019-10-14'
slug: report
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2019-10-14T17:15:26Z'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


-----

## Job Search Activities {.tabset .tabset-fade}

-----



> **My recent job research activities were partly guided by earlier preliminary plans laid out in the last report, as follows:**. 


> - Getting more routine and building up a suitable workflow in the development of webapplications, ie. coding applications (shiny apps/dashboards), building Docker images, deploying these applications via IBM cloud or similar, etc.

> **This point has been worked on and can be deemed to be successfull judged by the achieved end-products, namely: (1) An Rmarkdown interactive test-report on Swedish Demographics (at the European NUTS3 level) as well as family structure; (2) the creation of 2 dashboards, the first one based on the previously Rmarkdown test-report, the second one on European tourisme (and city weather conditions) driven by the wish to integrate and automate real-time streaming data by means of API calls and database storage. However, malfunctions in my IBM kubernetes cluster but mostly unsuccessful  dockerization process by means of my Digital Ocean VPS spoiled the deployments of these interactive reports/dashboards which however work smoothly on my local host, see a few snapshoots on this [Google Drive Folder](https://drive.google.com/open?id=1u7jhAQJw096tEY2zS7YB3T5Vd7ngEmYi)**. 

> - Getting more familiar with related tasks to the above mentioned workflow: security issues, stateless vs stateful applications, administration and monitoring, etc.

> **This point has been temporally put aside and left unprioritised**. 

> - Searching for suitable job opportunities either as a teacher position that matches my skill or as a data-analyst/research assitant in the social science field. 

> **This point has also been worked on by: (1) sending applications to teacher positions strong(anywhere) in Sweden - where the needs are present - given my terminating rental contract by the end of November (in Trelleborg) which gives me the freedom to move to my next job location in Sweden; (2) attending the Lund-IT "Mässe", albeit resulting job perspectives from this event are poor given the mismatch between my skills (dataanalysis from a statistical/machine learning standpoint that can be concretised using interactive web applications) and the ones asked during the event (more tailored towards web developpers that are well-acquainted with languages such as html/css/java and the like)**. 

----

> - Considering the above points, here comes a preliminary outline for my job search activities for the coming days:  

### **Priority 1: Teacher Position along with Freelance Activities**

##### **Working as a French/Maths teacher - Designing interactive Webapplications.**

----


> **My freedom of movement due to the termination of my rental contract opens better perspectives to get a fast teacher job anywhere in Sweden where the need arises. At the same time, given the risks of only getting a part-time teacher job that matches my qualifications, continuing dataanalysis projects in tandem with their deployments in the form of interactive web applications would support my efforts towards improving my skills that match the demand from the Swedish labour market while at the same time opening the doors for more job opportunities.**   


-----


### **Priority 2: Dataanalysis Internships along with Freelance Activities** 

##### **Working as a dataanalyst intern - Designing interactive Webapplications.**


-----


> **My freedom of movement also enables me to consider internship positions where new employers located anywhere in Sweden can judge my dataanalysis skills. As mentioned in the last Job Search report, internships in for instance dataanalysis or the participation in research projects in the economics or social science field where machine learning, multivariate analysis or social impact evaluation skills are in demand could be a possibility. This path has not been fully exploited yet given the strong competition in that field, my age as well as my lack of relevant experience being at odds with getting success in finding "normal" jobs. But I remain open and extremely attentive to datanalyst internships.

