---
title: "Job Search Report August-September 2019"
author: 'Samir Benjelloun'
date: '2019-09-12'
slug: new-rmarkdown
categories: ["R"]
tags: ["R Markdown", "job"]
subtitle: ''
summary: ''
authors: []
lastmod: '2019-09-12T09:09:01Z'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


-----

## Job Search Activities {.tabset .tabset-fade}

-----



> **My job research activities have to be placed under the context of the many degrees that I acquired during my university studies, my professional experiences as a teacher for example and the career path I wish to undertake for the near future**. 




### **Priority 1: Web developer**

##### **Designing interactive Webapplications for educational purposes.**

----


> Given the recent experiences in Denmark while teaching the topics that I feel most comfortable with, i.e. French and Geography, but most importantly some unfortunate frictions between me and my earlier school's leadership as well as a few colleagues, I consider that a career path change may be legitimate given my recent studies in economics, my interests in statistical tools and the recent experiences that I accumulated in coding web applications used under different Geography projects.    



> **Yet developing interactive webapplications to be consumed by students would also require additional skills beyond coding in R, the statistical programming language that I am familiar with.**


> Certainly, webapplications can be hosted by 3. parties, but for the sake of increased flexibility as well as for cost considerations, self-hosted solutions make more sense in my opinion. Yet this requires knowledge of:



> - The Linux OS and command line tools (Bash) as well as general administrative computer skills,
> - Version control tools such as Git for code storage, sharing and automating (CI/CD flows)
> - The containarisation of microservices, in particular tools such as Docker and Kubernetes, where different components of webapplications are made to function in clusters
> - Many related concepts/technologies working for the same goal of deploying final webapplications to be consumed by students, among others, networking and loadbalancing, storage and log monitoring, security issues, etc.
> - And further mastering of programming skills of Shiny Apps, Rmarkdown documents, Yaml files or the like. 



**Furthermore, in light of the many job possibilities in the field of web-development that demands skills in relatively new technologies such as Kubernetes, optimal CI/CD pipelines and the like, I consider this priority an opportune one.** 


-----


### **Priority 2: Teaching** 

##### **French, Maths, Geography or basic IT/programming skills.**


-----


> As a parallel undertaking, searching for teacher jobs with subjects such as French, Maths and Geography is continuously undertaken, but such job positions come rarerely as full-time positions, which is why the 1st priority was laid down and followed. In spite of my outlined priorities, I am open to take any teacher job in line with my competencies for the whole region of Skåne if needed, although I would expand my considerations and be ready to move anywhere in Sweden should a job position as webdeveloper turns out. 


-----


### **Priority 3: Data-analyst**

##### **Econometrics applied for social sciences.**


-----


> A third option is to consider jobs such as research assistant in economics or data-analysist at universities for instance in the field of machine learning, multivariate analysis or social impact evaluation. Realistically, my age and lack of relevant experience is at odd with getting success in finding such kind of jobs. Hence, as another option and if the choice presents itself, I would be happy to work in the field of data-analysis since closer to my interests (statistical programming, analysis and visualization). But so far, my efforts have been mainly put in getting myself ready for a webdeveloper position or, alternatively, in finding a suitable teacher position in the topics that matches my skills.

 

-----


## Planned activities for the near future ...

-----



> - Getting more routine and building up a suitable workflow in the development of webapplications, ie. coding applications (shiny apps/dashboards), building Docker images, deploying these applications via IBM cloud or similar, etc.
> - Getting more familiar with related tasks to the above mentioned workflow: security issues, stateless vs stateful applications, administration and monitoring, etc.
> - Searching for suitable job positions either as a teacher that matches my skill or data-analyst/research assitant in the social field as research assistant or the like. 